name: boringssl_ffi
description: "BoringSSL FFI Plugin"
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.3
  logging: ^1.0.0
  stack_trace: ^1.11.0

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true